### PR TITLE
Fullscreen mode for the editor

### PR DESCRIPTION
**Pull request by paulocheque**
https://github.com/paulocheque/guides-cms/commit/81544d71a30fb7effeeb514b34d00193be9815e0#commitcomment-17023463

### CODE REVIEW

**Comment by durden** [comment]
Looks great.  I was testing it out and found myself wanting to submit the form from full-screen mode itself.  What do you think about adding a submit button somewhere to the top of the editor?

We'll need to make sure the submission errors still show up when submitting from full-screen.  Maybe the errors could always use a bootstrap modal box?  Then, the errors could look the same in regular and full-screen mode.

Can you also move the stack selection to step 3 and then editing step 4?

This way the author most likely won't enter 'writing' mode until they've filled out all the other necessary fields.  I think picking the stack makes more sense at step 3 anyway; honestly not sure why I put it at 4 to begin with..

Finally, do you think it makes sense to have the escape character exit full-screen mode?

**Comment by paulocheque** [comment]
Great suggestions! I will apply all of them!

What about the "2 steps"? Should the fullscreen mode be optional like now?

**Comment by paulocheque** [comment]
Added the save button in the fullscreen mode. 

Also, I moved the article to the last step.

The fullscreen mode is automatically closed to display the error/success messages.

**Comment by durden** [comment]
Can you rebase this to avoid having the following commits in this PR?
- [Added an anchor link for every header like GitHub](https://github.com/pluralsight/guides-cms/pull/37/commits/d93a5cbcc6d8944550b9bca91913854366233035)
- [Animated header menu with links for hack.summit and hack.pledge](https://github.com/pluralsight/guides-cms/pull/37/commits/3abe475e249a2176b676cd3132a18849d8eae19f)

Maybe github is doing something weird.  I see those commits were on different branches, not your master.  However, the PR automatically pulled them in anyway.  Maybe you merged those changes to your master and pushed it, which then pulled them in here?

**Comment by paulocheque** [comment]
Absolutely. Actually I created this PR via master instead of the fs branch. I will update it.

**Comment by paulocheque** [comment]
Fixed.

**Pull request merged**
