### PR TITLE
Header Logo Menu with animated links to hack.pledge and hack.summit

### PR DESCRIPTION
**Pull request by paulocheque**
The font of the images are similar now.

### CODE REVIEW

**Comment by durden** [comment]
Is it possible to make all the letters line up vertically?  I'm not sure what the font is so if it's not a monospaced font then maybe it's not possible.  Another approach would be to narrow the distance between the icon and the first 'h' in 'hack' so it all lines up.  Here's what I see on a retina macbook:

screenshot 2016-04-13 17 54 54

It looks like the width of the icon next to the 'h' in 'hack' is different for each logo so maybe that's leading to the issue?

**Comment by durden** [comment]
Also need to make the summit and pledge logos work on a white background.  This is how the article pages look:
screenshot 2016-04-13 17 55 07

**Comment by durden** [comment]
On final idea.  Maybe the background of the hovered logo could change to a different shade of grey?  This way you can easily see what you're scrolling over.  The [hack.summit site](https://hacksummit.org) does this so maybe we can adapt that idea and use a shade of grey for the hover color.

**Comment by paulocheque** [comment]
Oh I missed this white navbar. I will check the changes. Maybe a transparent background may fixed too.

I am using images, for that reason we had fonts/space issues. I will try to edit this images to fix the alignment.

**Comment by durden** [comment]
I also ran into an issue on mobile.  Clicking the '+' shows the dropdown with all 3 logos.  However, I cannot hide the logos by clicking the 'x' next to the logos.  I tested it on a iPhone 5s with iOS 9.1 using Safari.  It's also broken in Chrome on iOS which I guess makes sense because they both use mobile webkit stuff.

**Comment by paulocheque** [comment]
I fixed the colors and alignment. It is pending the mobile issue.

**Comment by paulocheque** [comment]
I improve the layout for mobile devices and also checked the click issues.

I improve the click issues, but now it is working like this:
- if you click in the logo, go to the index
- if you click in the plus, open the menu
- if you click in another link/anchor in the page, the menu close
- if you click in the X button, nothing happens

For me it is fine that way, but I can add a js listener to this X link if necessary.

**Comment by durden** [comment]
The changes for white background and alignment issues look great.  I think the mobile changes make sense, no need to worry about a listener on the 'x' right now.  These changes are now on the production site.  Thanks!

**Pull request merged**
