### PR TITLE
Added a tooltip message into the disabled save button when there is n…

### PR DESCRIPTION
**Pull request by paulocheque**
…o title defined.

This PR fixes the tooltip issue in disabled buttons. This is a fix for this PR: https://github.com/pluralsight/guides-cms/pull/56

### CODE REVIEW

**Comment by durden** [comment]
Ah, the previous problem was not turning off the cursor events when disabled?

**Comment by paulocheque** [comment]
The bootstrap's tooltips does not work well in disabled elements. So I had to wrap the button in a div. But in the last PR I was missing some CSS things to make it work.

**Comment by durden** [comment]
Cool thanks for the info!  I tested it out and run into a weird issue that's a bit difficult to explain.  I've seen the `Save` button not enable sometimes **if** I select a previous title from the browser's history box.  I guess this doesn't trigger the same event?

Here's an example. Typing a title similar to something my browsers' (Safari) history has:

screenshot 2016-05-10 18 54 14

Now, when I hit tab to leave the `Title` field or click on the editor to refocus the `Save` button is not enabled even though there is a title:

screenshot 2016-05-10 18 56 05

Can you reproduce this or is it some weird Safari thing?

**Comment by paulocheque** [comment]
Nice catch! Yeah, it is a Safari issue: http://stackoverflow.com/questions/11708092/detecting-browser-autofill.

We can disable the autocomplete or try a lib for that: https://github.com/tbosch/autofill-event

What do you think?

**Comment by paulocheque** [comment]
Oh it is fixed with the blur event!

**Comment by durden** [comment]
Thanks!  I added a small comment on why the `blur` event is needed.

**Pull request merged**
