### PR TITLE
Added stack images

### PR DESCRIPTION
**Pull request by eh3rrera**
Added stack images for android, c/c++, go, java, node.js, php, sql, swift.

I tested the images locally and they looked good on 99x104 (for feature guides) and 40*43 (for the guide list).

Let me know if you need any modification.

### CODE REVIEW

**Comment by durden** [comment]
Thanks!!!  These are very helpful.  I added samples of each new image on the [staging site](http://pskb-stage.herokuapp.com).  I vote we merge all these and slightly edit the C++ logo.  The logo doesn't make it clear the stack is C **or** C++, and the shape is a bit small.  Maybe we could make the hexagon shape the same size as the C# logo and put something like 'C/C++' on it?  Just a suggestion, not sure how else to make it clear that C is also covered.

@edroman @prtkgpt @paulocheque What do you guys think?  Go to [this page](http://pskb-stage.herokuapp.com) for a sample of all the images.

**Comment by paulocheque** [comment]
Same here. I would improve the C#, C++ and PHP logos. Maybe it would be better to resize the image to the final size, instead of using SVG or let the browser resize the image. When the image is small in the browser, the font lose quality.

But the other images are perfect for me.

**Comment by eh3rrera** [comment]
Thanks @durden and @paulocheque.

What do you think about these versions?
https://dl.dropboxusercontent.com/u/40177530/c-c%2B%2B3.svg
https://dl.dropboxusercontent.com/u/40177530/php2.svg

For the C/C++ logo, I divided the hexagon into two parts and make it a little bigger than the C# logo.
For the PHP logo, I changed the font style.

I think they look better, but feel free to tell me if they need more changes.

**Comment by prtkgpt** [comment]
@durden thanks for testing everything. 
screen shot 2016-06-13 at 4 17 39 pm

@eh3rrera  notice the blur in bigger JS image under featured tutorial. We can fix that in next push by having two sizes for all coding language logos.

**Comment by durden** [comment]
I think we should avoid having two sizes if we can. The svg icons work
pretty well so far and the JS icon came from our own in-house designer.

**Comment by durden** [comment]
@prtkgpt I think the blur in the JS image is that there is a thin grey border around the image itself.  @eh3rrera would you mind taking a shot at removing that thin border?  In fact, I think the C# logo has a similar border.

**Comment by durden** [comment]
@eh3rrera I love your mockup for the C/C++ logo.  The PHP logo also looks much better.  Could you add both of these as a new commit (along with the JS and C# logo cleanups if you have time) to this PR?

Thanks again for all the image help @eh3rrera!  We really appreciate it!

**Comment by durden** [comment]
On second thought, that JS image is blurry as @prtkgpt mentioned regardless of the thin border around it.  Any ideas on how to clean this up?

I really like the idea of using just 1 SVG icon instead of separate image sizes.  However, I'm not front-end expert so I'm not sure the best practices for letting the browser resize, controlling the size in the layout so all images are roughly the same size, keeping the image from looking bad when growing, etc.  I think the images look pretty good when small but don't scale to well when used in the 'featured' section.  @paulocheque could you try some of your suggestions of letting the browser resize it and see if that helps?  @eh3rrera do you have any suggestions?  Maybe the best approach is to have separate sizes?

**Comment by durden** [comment]
One downside of using SVG images is Facebook's Open Graph sharing mechanism [doesn't support them](http://stackoverflow.com/questions/21636503/use-svg-image-as-ogimage).  I manually tested this just to make sure it's still the case, and it's still doesn't work.

For reference, I've been testing using the stack images as the `og:image` property when sharing things with Facebook.

Is this a big enough downside to warrant using png/jpg and multiple sizes for the stack images?

**Comment by eh3rrera** [comment]
@durden @prtkgpt @paulocheque 

I remade the C# and JS logos and they look much better now:
https://dl.dropboxusercontent.com/u/40177530/front-end-javascript.svg
https://dl.dropboxusercontent.com/u/40177530/microsoft-net.svg

However, most of these images are not "true" SVG, they just "wrap" a PNG image (for example, open the Go and the Python logos in a text editor and compare them).

So if SVG images are not supported by Facebook's Open Graph sharing mechanism maybe it's a good idea to use PNGs directly.

I'm not front-end expert either, but if we have a big enough image, we can scale down the image with no loss in quality. The feature guide image is 99x104 and the other size is 40x43, so all images, for example, can be PNGs of size 200x210 at just a few KBs.

I'll wait for your comments to update the PR. Thanks.

**Comment by durden** [comment]
Awesome. The new images look great. I'd say we go with your suggestion of
making large-ish png images that can scale between the two sizes and
removing the svg icons altogether then. Any downsides that anyone can think
of?

**Comment by eh3rrera** [comment]
@durden 

I changed all logos to PNG. Tested locally and everything looks good.

Comments or modifications are more than welcome.

**Comment by durden** [comment]
Thanks @eh3rrera!  I'll test it this week and post feedback.  Really appreciate all the help!

**Comment by eh3rrera** [comment]
Great, thanks!

**Comment by durden** [comment]
The small icons look great!  Again, really appreciate all your help!

I noticed a **small** thin white border around the image when we size it up for the 'featured' guide section.  I tested it with images for python and nodejs.  Here are some screenshots to show this.

screenshot 2016-06-23 09 30 30
screenshot 2016-06-23 09 31 16

I'm guessing this shows up on the smaller version too, but it's too small to notice.  Can anyone else see this or are my eyes deceiving me?

**Comment by MicroTransactionsMatterToo** [comment]
I'm guessing that could be fixed by using SVG's, assuming you aren't already

Otherwise, it should just be fixed by exporting to PNG without a background from Illustrator

**Comment by durden** [comment]
Our current approach is using SVGs.  However, [there are downsides](https://github.com/pluralsight/guides-cms/pull/89#issuecomment-225832968) so we're going to be switching to PNGs, which is part of this PR.  You can read above to see more on the discussion of SVG vs. PNG.

**Comment by MicroTransactionsMatterToo** [comment]
Yeah, some browsers don't like SVG's and they are problematic when scaling

**Comment by eh3rrera** [comment]
Hey @durden 

My mistake, I exported the images with the wrong settings. They're already corrected.

I also added the logos for the rest of the stacks:
- Big Data
- Clojure
- Erlang
- Haskell
- HTML/CSS
- Lua
- Objective C
- Scala

For the following, as they don't have logos, I just put the words over a background inspired by the Pluralsight logo colors:
- APIs
- NoSQL
- Software Engineering Practices

What do you think?

The only missing category is Others, but I can't think of anything...

**Comment by MicroTransactionsMatterToo** [comment]
Probs just a toolbox or gears would work. Otherwise, maybe just a generic bit of code, with a nice background

**Comment by eh3rrera** [comment]
Thanks @MicroTransactionsMatterToo, great idea, a gear works great!

I'm no completely certain about the APIs, NoSQL, and Software Engineering logos, so I created another version:
https://dl.dropboxusercontent.com/u/40177530/pngs/interesting-apis2.png
https://dl.dropboxusercontent.com/u/40177530/pngs/no-sql-databases2.png
https://dl.dropboxusercontent.com/u/40177530/pngs/software-engineering-best-practices2.png

So overall, what do you guys think?

**Comment by durden** [comment]
Looks great @eh3rrera!  I had to rename the file for nosql slightly so it showed up, but that's nothing compared to the amount of work you did!

**Comment by durden** [comment]
I've created sample guides for every stack on the [staging site](http://pskb-stage.herokuapp.com) for everyone to see.

**Comment by durden** [comment]
These changes are now on the [production site](http://tutorials.pluralsight.com).

**Pull request merged**
